image: 'rust:latest'

stages:
    - build

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
before_script:
  - apt-get update -qq
  - apt-get install -qq build-essential curl git

build:linux:
  stage: build
  before_script:
    - apt-get update && apt-get -y install cmake && apt-get install libcairo2-dev
  script:
    - cargo build
  cache:
    paths:
      - cargo/
      - target/
      
build:web:
  stage: build
  before_script:
    - cargo install --force cargo-web
  script:
    - cargo web build -p orbgl
  cache:
    paths:
      - cargo/
      - target/

# build:redox:
#   stage: build
#   variables:
#     CC: "x86_64-unknown-redox-gcc"
#   before_script:
#     - apt-get update -qq
#     - apt-get install -qq build-essential curl git gnupg software-properties-common apt-transport-https
#     - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AA12E97F0881517F
#     - add-apt-repository 'deb https://static.redox-os.org/toolchain/apt /'
#     - apt-get update -qq && apt-get install -qq x86-64-unknown-redox-gcc
#     - rustup default nightly
#     - rustup target add x86_64-unknown-redox
#   script:
#     - cargo build --target x86_64-unknown-redox
#   cache:
#     paths:
#       - cargo/
#       - target/
